name: cdmi
max_lag: 3
cdmi_epochs: 15
cdmi_pred_len: 1
cdmi_train_len: 111
cdmi_num_layers: 4
cdmi_num_samples: 5
cdmi_num_cells: 40
cdmi_dropout_rate: 0.1
cdmi_step_size: 1
cdmi_num_sliding_win: 15
cdmi_alpha: 0.10
cdmi_freq: null
cdmi_repo_path: null
cdmi_python_bin: null
cdmi_model_name: "cdmi_model.sav"
cdmi_plot_forecasts: False
cdmi_timeout_seconds: null
cdmi_verbose_failures: False
