defaults:
  - data_preprocess: default_preprocessing
  - _self_

label_path: "datasets/traffic_city_traffic_m_speed__category__1_0/debug_set_3_10k/east.p"
data_path: "product/traffic_city_traffic_m_speed__category__1_0"
save_path: "results/"
save_full_out: True

remove_diagonal: True
restrict_to: -1
dt_preprocess: True
n_jobs: 1
chunk_size: 128

data_preprocess:
  resolution: "5min"
  interpolate: True
  subset_month: False
  subset_year: False
  subsample: 1
  normalize: False
  remove_trailing_nans_early: False
  fill_remaining_nans_with_zero: True

methods:
  - name: var
    max_lag: 3
    var_absolute_values: True
    map_to_summary_graph: "max"
    var_min_std: 1.0e-12
    var_verbose_failures: False
  - name: corr
    corr_absolute_values: True
  - name: lagcorr
    max_lag: 3
    lagcorr_absolute_values: True
    map_to_summary_graph: "max"
